import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export default class ItemService {
  items = [
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },

    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
  ];
}
