import { Component } from '@angular/core';

@Component({
  selector: 'app-catalogue',
  templateUrl: './catalogue.component.html',
  styleUrls: ['./catalogue.component.css'],
})
export class CatalogueComponent {
  p: number = 1;

  items = [
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },

    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
    {
      title: 'salon',
      subTitle: 'salon de marque',
      height: 42,
      width: 45,
      price: 200.96,
      image: '../../../assets/images/home-img-1.jpg',
    },
  ];
}
